//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtdi_gatelog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vtdi_gatelog_dbEntities : DbContext
    {
        public vtdi_gatelog_dbEntities()
            : base("name=vtdi_gatelog_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gateinout> Gateinouts { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Itemtodeclear> Itemtodeclears { get; set; }
        public virtual DbSet<purpose> purposes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
    }
}
