//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtdi_gatelog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gateinout
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public int VehicleTypeID { get; set; }
        public string PlateNumber { get; set; }
        public int PurposeID { get; set; }
        public int ItemstodeclereID { get; set; }
        public Nullable<System.DateTime> Datetimein { get; set; }
        public Nullable<System.DateTime> Datetimeout { get; set; }
        public int UserID { get; set; }
    
        public virtual Itemtodeclear Itemtodeclear { get; set; }
        public virtual purpose purpose { get; set; }
        public virtual User User { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
